### ISSUE TITLE
The test is failed. (npm install)

### ISSUE THREAD

**Issue by justkost** [catamphetamine/react-isomorphic-render#57]
_Node v8.9.0
NPM v5.5.1_

exports
    ✓ should export ES6
    ✓ should export ES5
    1) should export rendering service

  3 passing (3s)
  1 failing

  **1) exports should export rendering service:
     Error: Cannot find module '../render on client'**
      at require (internal/module.js:11:18)
      at Object.<anonymous> (build/react-router/render.js:28:23)
      at loader (node_modules/babel-register/lib/node.js:144:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:154:7)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (build/server/render.js:63:15)
      at loader (node_modules/babel-register/lib/node.js:144:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:154:7)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (build/server/server.js:29:15)
      at loader (node_modules/babel-register/lib/node.js:144:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:154:7)
      at require (internal/module.js:11:18)
      at Object.<anonymous> (server.js:3:18)
      at loader (node_modules/babel-register/lib/node.js:144:5)
      at Object.require.extensions.(anonymous function) [as .js] (node_modules/babel-register/lib/node.js:154:7)
      at require (internal/module.js:11:18)
      at Context.<anonymous> (test/exports.js:163:18)

**Comment by catamphetamine** [comment]
Yes, the push to github repo didn't go through, pushed the fix now.
